import datetime as dt
import math
import random

import torch

import matcha.utils.monotonic_align as monotonic_align
from matcha import utils
from matcha.models.baselightningmodule import BaseLightningClass
from matcha.models.components.flow_matching import CFM
from matcha.models.components.text_encoder import TextEncoder
from matcha.utils.model import (
    denormalize,
    duration_loss,
    duration_loss_weight,
    duration_loss_weight_frame,
    duration_loss_sample,
    fix_len_compatibility,
    generate_path,
    sequence_mask,
)

log = utils.get_pylogger(__name__)


class MatchaTTS(BaseLightningClass):  # 🍵
    def __init__(
        self,
        n_vocab,
        n_spks,
        spk_emb_dim,
        n_feats,
        encoder,
        decoder,
        cfm,
        data_statistics,
        out_size,
        optimizer=None,
        scheduler=None,
        prior_loss=True,
        use_precomputed_durations=False,
        delta=1.,
        strategy="quadratic",
        max_alpha=0.5,
        min_alpha=0.0,
        dynamic_type="weighted_sum",
    ):
        super().__init__()

        self.save_hyperparameters(logger=False)

        self.n_vocab = n_vocab
        self.n_spks = n_spks
        self.spk_emb_dim = spk_emb_dim
        self.n_feats = n_feats
        self.out_size = out_size
        self.prior_loss = prior_loss
        self.use_precomputed_durations = use_precomputed_durations

        if n_spks > 1:
            self.spk_emb = torch.nn.Embedding(n_spks, spk_emb_dim)

        self.encoder = TextEncoder(
            encoder.encoder_type,
            encoder.encoder_params,
            encoder.duration_predictor_params,
            n_vocab,
            n_spks,
            spk_emb_dim,
        )

        self.decoder = CFM(
            in_channels=2 * encoder.encoder_params.n_feats,
            out_channel=encoder.encoder_params.n_feats,
            cfm_params=cfm,
            decoder_params=decoder,
            n_spks=n_spks,
            spk_emb_dim=spk_emb_dim,
        )
        self.delta = delta
        self.strategy = strategy
        self.dynamic_type = dynamic_type
        self.max_alpha = max_alpha
        self.min_alpha = min_alpha

        self.update_data_statistics(data_statistics)

    @torch.inference_mode()
    def synthesise(self, x, x_lengths, n_timesteps, temperature=1.0, spks=None, length_scale=1.0):
        """
        Generates mel-spectrogram from text. Returns:
            1. encoder outputs
            2. decoder outputs
            3. generated alignment

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            n_timesteps (int): number of steps to use for reverse diffusion in decoder.
            temperature (float, optional): controls variance of terminal distribution.
            spks (bool, optional): speaker ids.
                shape: (batch_size,)
            length_scale (float, optional): controls speech pace.
                Increase value to slow down generated speech and vice versa.

        Returns:
            dict: {
                "encoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Average mel spectrogram generated by the encoder
                "decoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Refined mel spectrogram improved by the CFM
                "attn": torch.Tensor, shape: (batch_size, max_text_length, max_mel_length),
                # Alignment map between text and mel spectrogram
                "mel": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Denormalized mel spectrogram
                "mel_lengths": torch.Tensor, shape: (batch_size,),
                # Lengths of mel spectrograms
                "rtf": float,
                # Real-time factor
        """
        # For RTF computation
        t = dt.datetime.now()

        if self.n_spks > 1:
            # Get speaker embedding
            spks = self.spk_emb(spks.long())

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, spks)

        w = torch.exp(logw) * x_mask
        w_ceil = torch.ceil(w) * length_scale
        y_lengths = torch.clamp_min(torch.sum(w_ceil, [1, 2]), 1).long()
        y_max_length = y_lengths.max()
        y_max_length_ = fix_len_compatibility(y_max_length)

        # Using obtained durations `w` construct alignment map `attn`
        y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)
        attn = generate_path(w_ceil.squeeze(1), attn_mask.squeeze(1)).unsqueeze(1)

        # Align encoded text and get mu_y
        mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
        mu_y = mu_y.transpose(1, 2)
        encoder_outputs = mu_y[:, :, :y_max_length]

        # Generate sample tracing the probability flow
        decoder_outputs = self.decoder(mu_y, y_mask, n_timesteps, temperature, spks)
        decoder_outputs = decoder_outputs[:, :, :y_max_length]

        t = (dt.datetime.now() - t).total_seconds()
        rtf = t * 22050 / (decoder_outputs.shape[-1] * 256)

        return {
            "encoder_outputs": encoder_outputs,
            "decoder_outputs": decoder_outputs,
            "attn": attn[:, :, :y_max_length],
            "mel": denormalize(decoder_outputs, self.mel_mean, self.mel_std),
            "mel_lengths": y_lengths,
            "rtf": rtf,
        }
    
    def apply_strategy(self, losses, delta=1.0, strategy="linupper"): 
        if strategy=="linupper": 
            return torch.minimum(losses + delta ,delta * torch.ones_like( losses)) 
        elif strategy=="uniform": 
            return losses 
        elif strategy=="quadratic": 
            return 1 - losses**2 / delta**2
        elif strategy=="extremes": 
            return torch.abs(losses) 
        else: 
            raise NotImplementedError
    
    def scale_losses(self, losses,r): 
        return torch.exp(losses/r)

    # data will from /mnt/md1/user_wago/Matcha-TTS/matcha/models/baselightningmodule.py get_loss, modify it to count loss weight
    def forward(self, x, x_lengths, y, y_lengths, spks=None, out_size=None, cond=None, durations=None, weights=None, frame_weight=None, pre_losses=None, indexs=None):
        """
        Computes 3 losses:
            1. duration loss: loss between predicted token durations and those extracted by Monotinic Alignment Search (MAS).
            2. prior loss: loss between mel-spectrogram and encoder outputs.
            3. flow matching loss: loss between mel-spectrogram and decoder outputs.

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            y (torch.Tensor): batch of corresponding mel-spectrograms.
                shape: (batch_size, n_feats, max_mel_length)
            y_lengths (torch.Tensor): lengths of mel-spectrograms in batch.
                shape: (batch_size,)
            out_size (int, optional): length (in mel's sampling rate) of segment to cut, on which decoder will be trained.
                Should be divisible by 2^{num of UNet downsamplings}. Needed to increase batch size.
            spks (torch.Tensor, optional): speaker ids.
                shape: (batch_size,)
        """
        # print(f'self.delta: {self.delta}')
        # input("")
        # count dynamic loss

        # print(f'self.delta: {self.delta.items()}')
        
        
        dynamic_weight = self.apply_strategy(pre_losses, delta=self.delta, strategy=self.strategy)
        
        # print(f'self.dynamic_type: {self.dynamic_type}')
        if self.dynamic_type=="weighted_sum":
            current_alpha = self.min_alpha +  self.trainer.current_epoch / self.trainer.max_epochs * (self.max_alpha - self.min_alpha)
            weights = weights * (1-current_alpha) + current_alpha * dynamic_weight
            if 0 in indexs:
                print(f"self.trainer.current_epoch: {self.trainer.current_epoch}, current_alpha: {current_alpha}")
                for index, weight, d_weight in zip(indexs, weights, dynamic_weight):
                    print(f'index: {index}, weight: {weight}, dynamic_weight: {d_weight}')
                print("")
        elif self.dynamic_type=="multiply" and self.trainer.current_epoch > 1:
            # print(f'weights: {weights}')
            r = self.max_alpha - self.trainer.current_epoch / self.trainer.max_epochs * (self.max_alpha - self.min_alpha)
            # print(f'r: {r}')
            current_alpha = self.scale_losses(dynamic_weight-dynamic_weight.max().item(),r=r)
            weights = current_alpha / current_alpha.sum() * weights
            if 0 in indexs:
                print(f"self.trainer.current_epoch: {self.trainer.current_epoch}, current_alpha: {current_alpha}")
                for index, weight, d_weight in zip(indexs, weights, dynamic_weight):
                    print(f'index: {index}, weight: {weight}, dynamic_weight: {d_weight}')
                print("")
        
        if self.n_spks > 1:
            # Get speaker embedding
            spks = self.spk_emb(spks)

        # print(f'weights in forward: {weights}')
        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, spks)
        y_max_length = y.shape[-1]

        y_mask = sequence_mask(y_lengths, y_max_length).unsqueeze(1).to(x_mask)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)

        if self.use_precomputed_durations:
            attn = generate_path(durations.squeeze(1), attn_mask.squeeze(1))
        else:
            # Use MAS to find most likely alignment `attn` between text and mel-spectrogram
            with torch.no_grad():
                const = -0.5 * math.log(2 * math.pi) * self.n_feats
                factor = -0.5 * torch.ones(mu_x.shape, dtype=mu_x.dtype, device=mu_x.device)
                y_square = torch.matmul(factor.transpose(1, 2), y**2)
                y_mu_double = torch.matmul(2.0 * (factor * mu_x).transpose(1, 2), y)
                mu_square = torch.sum(factor * (mu_x**2), 1).unsqueeze(-1)
                log_prior = y_square - y_mu_double + mu_square + const

                attn = monotonic_align.maximum_path(log_prior, attn_mask.squeeze(1))
                attn = attn.detach()  # b, t_text, T_mel

        # Compute loss between predicted log-scaled durations and those obtained from MAS
        # refered to as prior loss in the paper
        logw_ = torch.log(1e-8 + torch.sum(attn.unsqueeze(1), -1)) * x_mask
        if frame_weight is not None:
            dur_loss = duration_loss_weight_frame(logw, logw_, x_lengths, weights, frame_weight=frame_weight)
        else: 
            dur_loss = duration_loss_weight(logw, logw_, x_lengths, weights)

        non_weight_dur_loss = duration_loss_sample(logw, logw_, x_lengths)
        
        # Cut a small segment of mel-spectrogram in order to increase batch size
        #   - "Hack" taken from Grad-TTS, in case of Grad-TTS, we cannot train batch size 32 on a 24GB GPU without it
        #   - Do not need this hack for Matcha-TTS, but it works with it as well
        if not isinstance(out_size, type(None)):
            max_offset = (y_lengths - out_size).clamp(0)
            offset_ranges = list(zip([0] * max_offset.shape[0], max_offset.cpu().numpy()))
            out_offset = torch.LongTensor(
                [torch.tensor(random.choice(range(start, end)) if end > start else 0) for start, end in offset_ranges]
            ).to(y_lengths)
            attn_cut = torch.zeros(attn.shape[0], attn.shape[1], out_size, dtype=attn.dtype, device=attn.device)
            y_cut = torch.zeros(y.shape[0], self.n_feats, out_size, dtype=y.dtype, device=y.device)

            y_cut_lengths = []
            for i, (y_, out_offset_) in enumerate(zip(y, out_offset)):
                y_cut_length = out_size + (y_lengths[i] - out_size).clamp(None, 0)
                y_cut_lengths.append(y_cut_length)
                cut_lower, cut_upper = out_offset_, out_offset_ + y_cut_length
                y_cut[i, :, :y_cut_length] = y_[:, cut_lower:cut_upper]
                attn_cut[i, :, :y_cut_length] = attn[i, :, cut_lower:cut_upper]

            y_cut_lengths = torch.LongTensor(y_cut_lengths)
            y_cut_mask = sequence_mask(y_cut_lengths).unsqueeze(1).to(y_mask)

            attn = attn_cut
            y = y_cut
            y_mask = y_cut_mask

        # Align encoded text with mel-spectrogram and get mu_y segment
        mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
        mu_y = mu_y.transpose(1, 2)

        # Compute loss of the decoder
        # diff_loss, _ = self.decoder.compute_loss(x1=y, mask=y_mask, mu=mu_y, spks=spks, cond=cond)
        diff_loss, _ = self.decoder.compute_loss_weight(x1=y, mask=y_mask, mu=mu_y, spks=spks, cond=cond, weights=weights, frame_weight=frame_weight)
        non_weight_diff_loss, _ = self.decoder.compute_loss_sample(x1=y, mask=y_mask, mu=mu_y, spks=spks, cond=cond)
        # ori_diff_loss, _ = self.decoder.compute_loss(x1=y, mask=y_mask, mu=mu_y, spks=spks, cond=cond)
        
        # loss_diff = abs(ori_diff_loss - non_weight_diff_loss.sum())
        # # 檢查差距是否超過 0.5
        # if loss_diff > 0.2:
        #     print(f"差距過大，終止程式。ori_diff_loss: {ori_diff_loss}, non_weight_diff_loss: {non_weight_diff_loss}")
        #     exit()
        
        # print(f'non_weight_diff_loss.sum(): {non_weight_diff_loss.sum()}')
        # print(f'ori: {ori}')
        # input("")

        if self.prior_loss:
            # non_weight_prior_loss = torch.sum(0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask)
            # non_weight_prior_loss = non_weight_prior_loss / (torch.sum(y_mask) * self.n_feats)
            
            non_weight_prior_loss = 0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask
            non_weight_prior_loss = non_weight_prior_loss.sum(dim=(1, 2)) / (torch.sum(y_mask) * self.n_feats)
            
            # ori_prior_loss = torch.sum(0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask)
            # ori_prior_loss = ori_prior_loss / (torch.sum(y_mask) * self.n_feats)

            if frame_weight is not None:
                B, _, T = y.shape  # B 為 batch_size, T 為時間長度
                prior_loss = torch.zeros(B, device=y.device)
                
                for i in range(B):
                    sample_loss = torch.zeros(1, device=y.device)

                    frame_data = frame_weight[i]
                    for j in range(0, len(frame_data), 3):  # 每 3 個元素為一組 (s, t, fw)
                        s, t, fw = frame_data[j], frame_data[j+1], frame_data[j+2]
                        start, end = int(s * T), int(t * T)

                        if start < end:  # 確保區間有效
                            # 提取當前區間的預測和真實值
                            segment_y = y[i, :, start:end]  # Shape: (n_feats, end-start)
                            segment_mu_y = mu_y[i, :, start:end]  # Shape: (n_feats, end-start)
                            segment_y_mask = y_mask[i, :, start:end]  # Shape: (1, end-start)
                            
                            # 計算當前區間的 loss
                            interval_loss = torch.sum(0.5 * ((segment_y - segment_mu_y) ** 2 + math.log(2 * math.pi)) * segment_y_mask)
                            
                            # 加上 frame weight
                            sample_loss += interval_loss * fw

                    # 加上樣本級別權重
                    sample_loss *= weights[i]
                    prior_loss[i] = sample_loss

                # Final prior_loss after considering all segments
                prior_loss = prior_loss / (torch.sum(y_mask) * self.n_feats)  # Normalize by the number of segments
            else:
                prior_loss = torch.sum((0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask).permute(1, 2, 0) * weights)
                prior_loss = prior_loss / (torch.sum(y_mask) * self.n_feats)
        else:
            prior_loss = 0
            non_weight_prior_loss = [0]*len(weights)

        # ori_prior_loss = torch.sum(0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask)
        # ori_prior_loss = ori_prior_loss / (torch.sum(y_mask) * self.n_feats)
        
        # loss_diff = abs(ori_prior_loss - non_weight_prior_loss.sum())
        # # 檢查差距是否超過 0.5
        # if loss_diff > 0.2:
        #     print(f"差距過大，終止程式。ori_prior_loss: {ori_prior_loss}, non_weight_prior_loss: {non_weight_prior_loss}")
        #     exit()
        
        # print(f'ori_prior_loss: {ori_prior_loss}')
        # print(f'non_weight_prior_loss.sum: {non_weight_prior_loss.sum()}')
        # input("")
        #! may it chnage on dev epoch?
        if self.trainer.training:
            # print(f'non_weight_prior_loss: {non_weight_prior_loss.shape}')
            # print(f'non_weight_diff_loss: {non_weight_diff_loss.shape}')
            # print(f'non_weight_dur_loss: {non_weight_dur_loss.shape}')
            # print(f'indexs: {indexs.shape}')
            # input("")
            non_weight_prior_loss_value = non_weight_prior_loss.detach().cpu().tolist()
            non_weight_diff_loss_value = non_weight_diff_loss.detach().cpu().tolist()
            non_weight_dur_loss_value = non_weight_dur_loss.detach().cpu().tolist()
            self.trainer.datamodule.trainset.update_preloss(non_weight_prior_loss_value+non_weight_diff_loss_value+non_weight_dur_loss_value, indexs)
        return dur_loss, prior_loss, diff_loss, attn
    
    def on_epoch_end(self):
        #! may it chnage on dev epoch?
        if self.trainer.training:
            self.trainer.datamodule.trainset.normolize_preloss(self.delta)